### ISSUE TITLE
Ionic app not recognizing speech in android mobile

### ISSUE THREAD

**Issue by mailmrmanoj** [macdonst/SpeechRecognitionPlugin#57] opened 2016-05-13 11:26 UTC
Can anyone pls see this issue [http://stackoverflow.com/questions/37158366/ionic-app-not-recognizing-speech-in-android-mobile](url)

**Comment by jcesarmobile** [comment] 2016-05-16 06:44
Duplicate of https://github.com/macdonst/SpeechRecognitionPlugin/issues/56

**Closed by jcesarmobile** 2016-05-16 06:44 UTC

**Comment by mailmrmanoj** [comment] 2016-05-17 05:24
I wanted to design an ionic app that listens to voice commands by following the tutorial here But the app seems to recognize the voice commands over the microphone if tested on my computer using the var recognition = new webkitSpeechRecognition(); //To Computer

But this dosen't seem to work on my android device..
var recognition = new SpeechRecognition(); // To Device
