### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by videmort** [macdonst/SpeechRecognitionPlugin#69] opened 2016-09-26 19:19 UTC
When you try to do voice record 3-4 times app crashes.

Cordova version 6.2.0
Platform iOS Cordova 4.1.1

**Comment by Selvam75** [comment] 2016-09-27 18:37
I can't able to run the app at first time and ever in iOS only.android is working fine

**Comment by jcesarmobile** [comment] 2016-09-27 19:14
@Selvam75 are you testing on an iOS 10 device? I think the problem is the microphone permission
If you are testing on iOS 10, can you create a new issue about it?

**Comment by ajay2799** [comment] 2016-10-11 03:20
is there a solution to the microphone permission crash on iOS 10?

**Comment by jcesarmobile** [comment] 2016-10-11 07:08
@ajay2799 I was planning on working into it tomorrow.
Can you create a new issue?

As a workaround you can install the cordova-plugin-media-capture

**Comment by jcesarmobile** [comment] 2016-10-12 21:57
@Selvam75 @ajay2799 I've fixed the iOS 10 crash. Next time, please, open a new issue instead of commenting on an existing one if it's different.

@videmort I've updated iSpeech SDK, let me know if the crash is fixed, I've tried like 20 times in a row and didn't crash on an iPad 4 with iOS 10.

**Comment by jcesarmobile** [comment] 2016-10-31 10:36
No feedback after 19 days and I couldn't reproduce with latest version, so closing the issue.

**Closed by jcesarmobile** 2016-10-31 10:36 UTC
